#!/bin/sh
#
### BEGIN INIT INFO
# Provides:		reth
# Required-Start:	$remote_fs $syslog $networking
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	Start and stop the reth daemon
### END INIT INFO
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/reth
NAME=reth
DESC="Reth Node"
PIDFILE=/var/run/reth.pid
LOGFILE=/tmp/reth.log

# dd if=/dev/urandom bs=32 count=1 2>/dev/null | hexdump -v -e '1/1 "%02x"' > /var/volatile/jwt.hex
start() {
	echo -n "Starting $DESC: "
	mount -o remount,size=90% /var/volatile
	echo "0x4c5a4856e3873434d51de798c8e4f17ca2dcc2ccd42cb72c8446db819fe69489" > /var/volatile/jwt.hex
	start-stop-daemon -S -p $PIDFILE -N -10 -b -a /bin/sh -- -c "exec ${DAEMON} \
		node \
		--full \
		--datadir "/var/volatile/reth" \
		--authrpc.addr 0.0.0.0 \
		--authrpc.jwtsecret "/var/volatile/jwt.hex" \
		--authrpc.port 8551 \
		--http \
		--http.addr 0.0.0.0 \
		--http.port 8545 \
		--http.api "eth,net,web3,trace,rpc,debug,txpool" \
		--ws \
		--ws.addr 0.0.0.0 \
		--ws.port 8546 \
		--ws.api "eth,net,trace,web3,rpc,debug,txpool" \
		--log.stdout.format json \
		--log.file.max-files 0 \
		2>&1 | tee ${LOGFILE}"
	echo "$NAME."
}

stop() {
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	echo "$NAME."
}
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|reload}" >&2
	exit 1
	;;
esac
exit 0
